name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package add
        run: npx jsr publish
        working-directory: packages/add

      - name: Publish package calc
        run: npx jsr publish
        working-directory: packages/calc
